scrape_configs:
  - job_name: 'nginx'
    metrics_path: /nginx_status
    static_configs:
      - targets: ['nginx:80']
  - job_name: 'node-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']
